# Generated by Django 3.2.12 on 2022-04-05 11:06

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_auto_20211015_0858"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ldapgroup",
            name="cn",
            field=ldapdb.models.fields.CharField(
                db_column="cn", max_length=200, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ldapperson",
            name="uid",
            field=ldapdb.models.fields.CharField(
                db_column="uid", max_length=200, primary_key=True, serialize=False
            ),
        ),
    ]
